command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    value: "https://skydio-analytics.cloud.databricks.com"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "2b54e8360234aba2"
  - name: DATABRICKS_TOKEN
    valueFrom: "DATABRICKS_TOKEN" 
