import os

DATABRICKS_HOST = os.environ["DATABRICKS_HOST"]
DATABRICKS_TOKEN = os.environ["DATABRICKS_TOKEN"]

print("DATABRICKS_HOST:", DATABRICKS_HOST)
print("DATABRICKS_TOKEN starts with:", DATABRICKS_TOKEN[:4])